import { archiveAssets } from "./archiveAssets.js";

const demoAsset = (key) => archiveAssets[key] || archiveAssets.portraitNeon;

export const demoUser = {
  username: "apix_user",
  full_name: "APIX Creator",
  photo_url: demoAsset("portraitNeon"),
  credits: 12450,
  referral_balance: 0,
  referral_link: "",
};

export const demoFeed = [
  {
    id: "demo-1",
    author: "Elysian",
    gen_type: "image",
    model: "gpt-image-2-text-to-image",
    prompt: "Кинематографичный портрет в розово-синем неоне, мокрый асфальт, премиальная детализация",
    likes_count: 2400,
    shares_count: 312,
    remixes: 82,
    created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    preview_url: demoAsset("portraitNeon"),
    result_url: demoAsset("portraitNeon"),
    preview_urls: [demoAsset("portraitNeon")],
    result_urls: [demoAsset("portraitNeon")],
  },
  {
    id: "demo-2",
    author: "SkyForge",
    gen_type: "video",
    model: "kling-3.0/video",
    prompt: "Архитектурный noir-интерьер с магентовыми линиями света, мрамор, стекло, глубина",
    likes_count: 1800,
    shares_count: 201,
    remixes: 44,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    preview_url: demoAsset("architecture"),
    result_url: demoAsset("architecture"),
    preview_urls: [demoAsset("architecture")],
    result_urls: [demoAsset("architecture")],
  },
  {
    id: "demo-3",
    author: "NeonSoul",
    gen_type: "image",
    model: "nano-banana-pro",
    prompt: "Готическая fashion-сцена, дым, чёрная ткань, розово-фиолетовый контровой свет",
    likes_count: 3100,
    shares_count: 432,
    remixes: 128,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    preview_url: demoAsset("fashion"),
    result_url: demoAsset("fashion"),
    preview_urls: [demoAsset("fashion")],
    result_urls: [demoAsset("fashion")],
  },
  {
    id: "demo-4",
    author: "DriveDreams",
    gen_type: "image",
    model: "seedream/5-pro-text-to-image",
    prompt: "Глянцевый суперкар под дождём, неоновые отражения, luxury ad photography",
    likes_count: 1200,
    shares_count: 178,
    remixes: 39,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    preview_url: demoAsset("car"),
    result_url: demoAsset("car"),
    preview_urls: [demoAsset("car")],
    result_urls: [demoAsset("car")],
  },
  {
    id: "demo-5",
    author: "ObjectLab",
    gen_type: "image",
    model: "seedream/5-pro-text-to-image",
    prompt: "Премиальный product shot, чёрный глянец, cyan rim light, luxury ecommerce",
    likes_count: 920,
    shares_count: 118,
    remixes: 31,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    preview_url: demoAsset("product"),
    result_url: demoAsset("product"),
    preview_urls: [demoAsset("product")],
    result_urls: [demoAsset("product")],
  },
  {
    id: "demo-6",
    author: "TimeStudio",
    gen_type: "image",
    model: "gpt-image-2-text-to-image",
    prompt: "Luxury watch campaign, velvet black background, magenta reflections, macro detail",
    likes_count: 1120,
    shares_count: 163,
    remixes: 47,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 55).toISOString(),
    preview_url: demoAsset("watch"),
    result_url: demoAsset("watch"),
    preview_urls: [demoAsset("watch")],
    result_urls: [demoAsset("watch")],
  },
  {
    id: "demo-7",
    author: "HaloMuse",
    gen_type: "video",
    model: "veo3_fast",
    prompt: "Лаунж в стиле futurist noir, мягкая камера, slow motion",
    likes_count: 1530,
    shares_count: 144,
    remixes: 51,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    preview_url: demoAsset("lounge"),
    result_url: demoAsset("lounge"),
    preview_urls: [demoAsset("lounge")],
    result_urls: [demoAsset("lounge")],
  },
  {
    id: "demo-8",
    author: "GlassWorks",
    gen_type: "image",
    model: "nano-banana-pro",
    prompt: "Abstract glass sculpture, glossy reflections, violet-cyan premium editorial frame",
    likes_count: 760,
    shares_count: 91,
    remixes: 22,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 63).toISOString(),
    preview_url: demoAsset("abstractGlass"),
    result_url: demoAsset("abstractGlass"),
    preview_urls: [demoAsset("abstractGlass")],
    result_urls: [demoAsset("abstractGlass")],
  },
  {
    id: "demo-9",
    author: "SculptorAI",
    gen_type: "image",
    model: "grok-imagine/text-to-image",
    prompt: "Мраморная муза в неоновом ореоле, глянцевый чёрный камень, premium poster art",
    likes_count: 840,
    shares_count: 96,
    remixes: 24,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 27).toISOString(),
    preview_url: demoAsset("editorialSculpture"),
    result_url: demoAsset("editorialSculpture"),
    preview_urls: [demoAsset("editorialSculpture")],
    result_urls: [demoAsset("editorialSculpture")],
  },
];

export const demoPrompts = [
  { id: "prompt-1", title: "Неоновый портрет", prompt: "Кинематографичный портрет в розово-синем неоне, мокрый асфальт, объёмный свет, премиальная детализация", category: "portrait", cover_url: demoAsset("portraitNeon"), likes_count: 892, uses_count: 1260 },
  { id: "prompt-2", title: "Архитектурный noir", prompt: "Тёмный премиальный интерьер, мрамор, стекло, магентовые линии света, editorial depth", category: "interior", cover_url: demoAsset("architecture"), likes_count: 756, uses_count: 980 },
  { id: "prompt-3", title: "Рекламный суперкар", prompt: "Премиальная автомобильная фотосъёмка ночью, дождь, неон, отражения, объектив 85mm", category: "commercial", cover_url: demoAsset("car"), likes_count: 642, uses_count: 744 },
  { id: "prompt-4", title: "Luxury product shot", prompt: "Предметная съёмка премиального продукта на бархатно-чёрном фоне, cyan rim light, macro detail", category: "product", cover_url: demoAsset("product"), likes_count: 538, uses_count: 612 },
];

export const demoImageModels = [
  { key: "gpt-image-2-text-to-image", model_key: "gpt-image-2-text-to-image", name: "GPT Image 2", display_name: "GPT Image 2", credits: 10, aspect_ratios: ["1:1", "4:5", "9:16", "16:9"], counts: [1, 2, 4] },
  { key: "nano-banana-pro", model_key: "nano-banana-pro", name: "Nano Banana Pro", display_name: "Nano Banana Pro", credits: 8, aspect_ratios: ["1:1", "3:4", "9:16", "16:9"], counts: [1] },
  { key: "seedream/5-pro-text-to-image", model_key: "seedream/5-pro-text-to-image", name: "Seedream 5 Pro", display_name: "Seedream 5 Pro", credits: 6, aspect_ratios: ["1:1", "4:5", "16:9"], counts: [1, 2] },
];

export const demoVideoModels = [
  { key: "kling-3.0/video", model_key: "kling-3.0/video", name: "Kling 3.0", display_name: "Kling 3.0", credits: 30, durations: [5, 10] },
  { key: "veo3_fast", model_key: "veo3_fast", name: "Veo Fast", display_name: "Veo Fast", credits: 35, durations: [5, 8] },
];

export const demoPlans = [
  { id: "p1", credits: 100, price_rub: 99, bonus_credits: 10 },
  { id: "p2", credits: 300, price_rub: 249, bonus_credits: 40 },
  { id: "p3", credits: 1000, price_rub: 799, bonus_credits: 200 },
  { id: "p4", credits: 3000, price_rub: 2199, bonus_credits: 750 },
];
